homepage: http://RyanScottLewis.github.io/cutback
repository: https://github.com/RyanScottLewis/cutback
issues: https://github.com/RyanScottLewis/cutback/issues
summary: System for smaller, more focused backups
description: |
  Cutback is a backup system with the goal of creating smaller, more focused backups by generating
  filtered file lists before archiving and keeping records of easily reaquirable files.
strategy: |
  1. Gather all files within search paths
    * Skip
      * Files matching exclusion patterns
      * Files matching record patterns
    * Save to `ID.manifest`
  2. Gather all files within search paths
    * Only
      * Files matching record patterns
    * Save to `ID.records`
  3. Archive files within the manifest
    * Only
      * Files within the manifest
    * Save to `ID.tar[.COMPRESSION-SUFFIX]`
  4. Create checksum
  5. Gather metadata
    * Backup
      * Date & time (UTC)
      * Search paths
      * Duration
    * Manifest
      * File count
      * Total file size
    * Archive
      * Compression
        * Enabled
        * Tool (gzip, xz, etc.)
        * Flags (passed to the tool)
      * Checksum
        * Tool (sha256sum, sha512sum, etc.)
        * Value
    * Save to `ID.{yaml,json}`
mit_license: This program is available as open source under the terms of the MIT License <http://opensource.org/licenses/MIT>.
options:
  - long:        help
    short:       h
    type:        bool
    description: Display help
  - long:        version
    short:       v
    type:        bool
    description: Display version
  - long:        config
    short:       c
    type:        string
    description: Configuration file path
  - long:        dry
    short:       D
    type:        bool
    description: Do not run system commands (dry run)
  - long:        output
    short:       o
    type:        string
    description: Output path
  - long:        date
    short:       d
    type:        date
    description: Date for the backup in YYYY-MM-DD format
  - long:        index
    short:       i
    type:        integer
    description: Index for the backup
  - long:        paths
    short:       p
    type:        list
    description: Search paths
  - long:        excludes
    short:       e
    type:        list
    description: Exclusion path patterns
  - long:        paths
    short:       r
    type:        list
    description: Record path patterns
  - long:        format
    short:       f
    type:        string
    description: Format of the metadata file
  - long:        progress
    short:       P
    type:        bool
    description: View progress
  - long:        compress
    short:       C
    type:        bool
    description: Compress archive
  - long:        compressor
    short:       c
    type:        string
    description: Compressor binary
controllers:
  application:
    description: Application actions
    actions:
      create:    Create all backup files
      help:      Display help
      version:   Display version
  manifest:
    description: List of all files in the archive
    actions:
      create:    Create the manifest
      read:      View manifest metadata
  records:
    description: List of files excluded from the archive, but kept a record of
    actions:
      create:    Create the records
      read:      View records metadata
  archive:
    description: Archive of files in the manifest
    actions:
      create:    Create the archive
      read:      View archive metadata
  checksum:
    description: Archive checksum
    actions:
      create:    Create the checksum
      read:      Verify the checksum
  metadata:
    description: Information about the backup
    actions:
      create:    Create the metadata
      read:      View the metadata
  config:
    description: Current configuration
    actions:
      create:    Dump the current configuration to file
      read:      View the current configuration

