name: cutback
version: 0.0.1
homepage: http://RyanScottLewis.github.io/cutback
repository: https://github.com/RyanScottLewis/cutback
issues: https://github.com/RyanScottLewis/cutback/issues
license: This program is available as open source under the terms of the MIT License <http://opensource.org/licenses/MIT>.
summary: System for smaller, more focused backups
description: |
  Cutback is a backup system with the goal of creating smaller, more focused backups by generating
  filtered file lists before archiving and keeping records of easily reaquirable files.
strategy: |
  1. Gather all files within search paths
    * Skip
      * Files matching exclusion patterns
      * Files matching record patterns
    * Save to `ID.manifest`
  2. Gather all files within search paths
    * Only
      * Files matching record patterns
    * Save to `ID.records`
  3. Archive files within the manifest
    * Only
      * Files within the manifest
    * Save to `ID.tar[.COMPRESSION-SUFFIX]`
  4. Create checksum
  5. Gather metadata
    * Backup
      * Date & time (UTC)
      * Search paths
      * Duration
    * Manifest
      * File count
      * Total file size
    * Archive
      * Compression
        * Enabled
        * Tool (gzip, xz, etc.)
        * Flags (passed to the tool)
      * Checksum
        * Tool (sha256sum, sha512sum, etc.)
        * Value
    * Save to `ID.{yaml,json}`
arguments:
  - name:        options
    description: Command-line options
    optional:    true
  - name:        controller # TODO: RENAME TO RESOURCE
    description: Controller to perform the action for
    optional:    true
  - name:        action
    description: Action to perform
    optional:    true
options:
  - name:        help
    short:       h
    type:        bool
    description: Display help
  - name:        version
    short:       v
    type:        bool
    description: Display version
  - name:        config
    short:       c
    type:        string
    description: Configuration file path
  - name:        dry
    short:       D
    type:        bool
    description: Do not run system commands (dry run)
  - name:        force
    short:       F
    type:        bool
    description: Force the action (create even if resource exists, etc)
  - name:        output
    short:       o
    type:        string
    description: Output path
  - name:        date
    short:       d
    type:        date
    description: Date for the backup in YYYY-MM-DD format
  - name:        index
    short:       i
    type:        integer
    description: Index for the backup
  - name:        paths
    short:       p
    type:        list
    description: Search paths
  - name:        excludes
    short:       e
    type:        list
    description: Exclusion path patterns
  - name:        paths
    short:       r
    type:        list
    description: Record path patterns
  - name:        format
    short:       f
    type:        string
    description: Format of the metadata file
  - name:        progress
    short:       P
    type:        bool
    description: View progress
  - name:        compress
    short:       C
    type:        bool
    description: Compress archive
  - name:        finder
    short:       S
    type:        string
    description: Finder command
  - name:        archiver
    short:       a
    type:        string
    description: Archiver command
  - name:        compressor
    short:       x
    type:        string
    description: Compressor command
  - name:        checker
    short:       s
    type:        string
    description: Checker (checksum) command
  - name:        reader
    short:       R
    type:        string
    description: Reader command
  - name:        viewer
    short:       w
    type:        string
    description: Viewer (progress) command
controllers:
  - name:            proxy
    description:     Proxy actions
    actions:
      - name:        help
        description: See application#help
      - name:        version
        description: See application#version
      - name:        create
        description: See backup#create
      - name:        read
        description: See backup#read
      - name:        update
        description: See backup#update
      - name:        destroy
        description: See backup#destroy
      - name:        verify
        description: See checksum#verify
      - name:        manifest
        description: See manifest#create
      - name:        records
        description: See records#create
      - name:        archive
        description: See archive#create
      - name:        checksum
        description: See checksum#create
      - name:        metadata
        description: See metadata#create
      - name:        config
        description: See config#create
      - name:        backup
        description: See backup#read
      - name:        log
        description: See log#read
  - name:            application
    description:     Application actions
    actions:
      - name:        help
        description: Display help
      - name:        version
        description: Display version
  - name:            backup
    description:     The current backup
    actions:
      - name:        create
        description: Create backup
      - name:        read
        description: View backup
      - name:        update
        description: Re-create backup
      - name:        destroy
        description: Destroy backup
      - name:        metadata
        description: View backup metadata
  - name:            manifest
    description:     List of all files in the archive
    actions:
      - name:        create
        description: Create manifest
      - name:        read
        description: View manifest
      - name:        update
        description: Re-create manifest
      - name:        destroy
        description: Destroy manifest
      - name:        metadata
        description: View manifest metadata
  - name:            records
    description:     List of files excluded from the archive, but kept a record of
    actions:
      - name:        create
        description: Create records
      - name:        read
        description: View records
      - name:        update
        description: Re-create records
      - name:        destroy
        description: Destroy records
      - name:        metadata
        description: View records metadata
  - name:            archive
    description:     Archive of files in the manifest
    actions:
      - name:        create
        description: Create archive
      - name:        read
        description: View archive
      - name:        update
        description: Re-create archive
      - name:        destroy
        description: Destroy archive
      - name:        metadata
        description: View archive metadata
  - name:            checksum
    description:     Archive checksum
    actions:
      - name:        create
        description: Create checksum
      - name:        read
        description: View checksum
      - name:        update
        description: Re-create checksum
      - name:        verify
        description: Verify checksum
      - name:        destroy
        description: Destroy checksum
  - name:            metadata
    description:     Information about the backup
    actions:
      - name:        create
        description: Create metadata
      - name:        read
        description: View metadata
      - name:        update
        description: Update metadata
      - name:        destroy
        description: Destroy metadata
  - name:            config
    description:     Current configuration
    actions:
      - name:        create
        description: Create config
      - name:        read
        description: View config
      - name:        update
        description: Update config
      - name:        destroy
        description: Destroy metadata
  - name:            log
    description:     Log
    actions:
      - name:        read
        description: View log
      - name:        destroy
        description: Destroy log

