---
  # Output path for backup
  output: "./tmp"

  # The list of paths to search for files to backup
  paths:
    - "/home"

  # The file patterns to exclude while searching
  excludes:
    - "*/.*"
    - "*/Art/*"
    - "*/Backups/*"
    - "*/Bookmarks/*"
    - "*/Downloads/*"
    - "*/Recreation/*"
    - "*/Science/*"
    - "*/VirtualBox\ VMs/*"
    - "*/sketchbook/*"

  # The file patterns to exclude while searching and keep a record of
  records:
    - "*/Pictures/*"
    - "*/Documents/Plans/*"

  # Compress the archive
  compress: true

  # Show progress of each step while performing
  progress: true

  # Format of the archive metadata
  format: "json"

