.TH man 1 "cutback" "0.1.0" "cutback"
.SH NAME
cutback \- System for smaller, more focused backups
.SH SYNOPSIS
\fBcutback\fR [\fIoptions\fR]
.SH DESCRIPTION
Cutback is a backup system with the goal of creating smaller, more focused backups by generating
filtered file lists before archiving and keeping records of easily reaquirable files.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help
.TP
\fB\-v\fR, \fB\-\-version\fR
Display version
.TP
\fB\-c\fR, \fB\-\-config\fR
Configuration file path

See \fIcutback(5)\fR for config file details.
.TP
\fB\-o\fR, \fB\-\-output\fR
Output path

\fBDefault:\fR \fI"."\fR
.TP
\fB\-d\fR, \fB\-\-date\fR
Date for the backup in YYYY-MM-DD format

\fBDefault:\fR The current date
.TP
\fB\-i\fR, \fB\-\-index\fR
Index for the backup

\fBDefault:\fR The largest index for the current date incremented by \fI1\fR or \fI0\fR
.TP
\fB\-p\fR, \fB\-\-paths\fR
Search paths
.TP
\fB\-e\fR, \fB\-\-excludes\fR
Exclusion path patterns
.TP
\fB\-r\fR, \fB\-\-records\fR
Record path patterns
.TP
\fB\-p\fR, \fB\-\-progress\fR
Enable viewing progress
.TP
\fB\-f\fR, \fB\-\-format\fR
Format of the metadata file

\fBValid:\fR \fI"yaml"\fR or \fI"json"\fR

\fBDefault:\fR \fI"yaml"\fR
.TP
\fBLIST VALUES\fR
Values passed to the \fB\-\-paths\fR, \fB\-\-excludes\fR, and \fB\-\-records\fR options are paths
delimited by semi-colon (;) characters:
.PP
.nf
.RS
.RS
--paths "/home;/srv;/etc"
.RE
.RE
.fi
.TP
\fBPATTERN VALUES\fR
Values passed to the \fB\-\-excludes\fR and \fB\-\-records\fR options are file patterns capable of using
wildcards:
.PP
.nf
.RS
.RS
--excludes "/srv/public/*/Videos/*"
.RE
.fi
.SH STRATEGY
.nf
1. Gather all files within search paths
  * Skip
    * Files matching exclusion patterns
    * Files matching record patterns
  * Save to `ID.manifest`
2. Gather all files within search paths
  * Only
    * Files matching record patterns
  * Save to `ID.records`
3. Archive files within the manifest
  * Only
    * Files within the manifest
  * Save to `ID.tar[.COMPRESSION-SUFFIX]`
4. Gather metadata
  * Backup
    * Date & time (UTC)
    * Search paths
    * Duration
  * Manifest
    * File count
    * Total file size
  * Archive
    * Compression
      * Enabled
      * Tool (gzip, xz, etc.)
      * Flags (passed to the tool)
    * Checksum
      * Tool (sha256sum, sha512sum, etc.)
      * Value
  * Save to `ID.{yaml,json}`
.fi
.SH SEE ALSO
.TP
\fBHomepage\fR
http://RyanScottLewis.github.io/cutback
.TP
\fBRepository\fR
https://github.com/RyanScottLewis/cutback
.TP
\fBIssues/Bugs\fR
https://github.com/RyanScottLewis/cutback/issues
.TP
\fBConfiguration\fR
\fIcutback(5)\fR
.SH LICENSE
This program is available as open source under the terms of the MIT License <http://opensource.org/licenses/MIT>.

