.TH man 1 "<%= name %>" "<%= version %>" "<%= name %>"
.SH NAME
<%= name %> \- <%= summary %>
.SH USAGE
\fB<%= name %>\fR [\fIOPTIONS\fR] [\fICONTROLLER\fR] [\fIACTION\fR]
.SH DESCRIPTION
<%= description %>
.SH OPTIONS
<%- options.each do |option| %>
<%= man_option(option) -%>
<% end %>
.TP
\fBList Values\fR
Values passed to the \fB\-\-paths\fR, \fB\-\-excludes\fR, and \fB\-\-records\fR options are paths
delimited by semi-colon (;) characters:
.PP
.nf
.RS
.RS
--paths "/home;/srv;/etc"
.RE
.RE
.fi
.TP
\fBPattern Values\fR
Values passed to the \fB\-\-excludes\fR and \fB\-\-records\fR options are file patterns capable of using
wildcards:
.PP
.nf
.RS
.RS
--excludes "/srv/public/*/Videos/*"
.RE
.fi
.SH CONTROLLERS & ACTIONS
<% app_controllers.each do |controller| -%>
.TP
\fB<%= controller.name %>\fR <%= controllers[controller.name]["description"] %>
<%- controller.actions.each do |action| %>
<%-= action.ljust(21) -%>
<% end %>
<% end %>
.SH STRATEGY
.nf
<%= strategy %>
.fi
.SH SEE ALSO
.TP
\fBHomepage\fR
<%= homepage %>
.TP
\fBRepository\fR
<%= repository %>
.TP
\fBIssues/Bugs\fR
<%= issues %>
.TP
\fBConfiguration\fR
\fI<%= name %>(5)\fR
.SH LICENSE
<%= mit_license %>

