.TH man 1 "<%= app.name %>" "<%= app.version %>" "<%= app.name %>"
.SH OUTLINE
<%= app.outline %>
.SH USAGE
<%= app.usage %>
.SH DESCRIPTION
<%= app.description -%>
.SH ARGUMENTS
<%= app.arguments %>
.TP
\fBDefaults\fR
When only a single argument is given, the controller is `proxy`.
.br
When no arguments are given, the controller is `proxy` and the action is `create`.
.SH OPTIONS
<%= app.options %>
.TP
\fBList Values\fR
Values passed to the \fB\-\-paths\fR, \fB\-\-excludes\fR, and \fB\-\-records\fR options are paths
delimited by semi-colon (;) characters:
.PP
.nf
.RS
.RS
--paths "/home;/srv;/etc"
.RE
.RE
.fi
.TP
\fBPattern Values\fR
Values passed to the \fB\-\-excludes\fR and \fB\-\-records\fR options are file patterns capable of using
wildcards:
.PP
.nf
.RS
.RS
--excludes "/srv/public/*/Videos/*"
.RE
.fi
.SH CONTROLLERS & ACTIONS
<%= app.controllers %>
.SH STRATEGY
.nf
<%= app.strategy %>
.fi
.SH SEE ALSO
.TP
\fBHomepage\fR
<%= app.homepage %>
.TP
\fBRepository\fR
<%= app.repository %>
.TP
\fBIssues/Bugs\fR
<%= app.issues %>
.TP
\fBConfiguration\fR
\fI<%= app.name %>(5)\fR
.SH LICENSE
<%= app.license %>

