name: cutback
version: 0.0.1-pre
homepage: http://RyanScottLewis.github.io/cutback
repository: https://github.com/RyanScottLewis/cutback
issues: https://github.com/RyanScottLewis/cutback/issues
releases: https://github.com/RyanScottLewis/cutback/releases
packages:
  "Arch Linux AUR": https://aur.archlinux.org/packages/cutback/
license: This program is available as open source under the terms of the MIT License <http://opensource.org/licenses/MIT>.
summary: Backup system with the goal of creating smaller, more focused backups.
description: |
  Cutback is a backup system with the goal of creating smaller, more focused backups by generating
  filtered file lists before archiving and keeping records of easily reaquirable files.
arguments:
  - name:        options
    description: Command-line options
    optional:    true

  - name:        controller # TODO: RENAME TO RESOURCE
    description: Controller to perform the action for
    optional:    true

  - name:        action
    description: Action to perform
    optional:    true

options:
  - name:        help
    description: Display help
    short:       h
    type:        bool
    default:     false

  - name:        version
    description: Display version
    short:       v
    type:        bool
    default:     false

  - name:        dry
    description: Do not run system commands (dry run)
    short:       D
    type:        bool
    default:     false

  - name:        force
    description: Force the action (create even if resource exists, etc)
    short:       F
    type:        bool
    default:     false

  - name:        config
    description: Configuration file path or directory
    short:       c
    type:        string

  - name:        output
    description: Output path
    short:       o
    type:        string
    default:     .

  - name:        date
    description: Date for the backup in YYYY-MM-DD format
    short:       d
    type:        date
    default:     Time.utc

  - name:        index
    description: Index for the backup
    short:       i
    type:        integer

  - name:        paths
    description: Search paths
    short:       p
    type:        list

  - name:        excludes
    description: Exclusion path patterns
    short:       e
    type:        list

  - name:        records
    description: Record path patterns
    short:       r
    type:        list

  - name:        format
    description: Format of the metadata file
    short:       f
    type:        string
    default:     yaml

  - name:        progress
    description: View progress
    short:       P
    type:        bool
    default:     false

  - name:        compress
    description: Compress archive
    short:       C
    type:        bool
    default:     false

  - name:        compress_level
    description: Compression level
    short:       l
    type:        integer
    default:     3

  - name:        compress_threads
    description: Compression threads (0 usually means all cores)
    short:       t
    type:        integer
    default:     0

  - name:        finder
    description: Finder command
    short:       S
    type:        string
    default:     find

  - name:        archiver
    description: Archiver command
    short:       a
    type:        string
    default:     tar

  - name:        compressor
    description: Compressor command
    short:       x
    type:        string
    default:     xz

  - name:        checker
    description: Checker (checksum) command
    short:       s
    type:        string
    default:     sha512sum

  - name:        reader
    description: Reader command
    short:       R
    type:        string
    default:     cat

  - name:        viewer
    description: Viewer (progress) command
    short:       w
    type:        string
    default:     pv

controllers:
  - name:            proxy
    description:     Proxy actions (default)
    actions:
      - name:        help
        description: See application#help

      - name:        version
        description: See application#version

      - name:        create
        description: See backup#create

      - name:        read
        description: See backup#read

      - name:        update
        description: See backup#update

      - name:        destroy
        description: See backup#destroy

      - name:        verify
        description: See checksum#verify

      - name:        manifest
        description: See manifest#create

      - name:        records
        description: See records#create

      - name:        archive
        description: See archive#create

      - name:        checksum
        description: See checksum#create

      - name:        metadata
        description: See metadata#create

      - name:        config
        description: See config#create

      - name:        backup
        description: See backup#read

      - name:        log
        description: See log#read

  - name:            application
    description:     Application actions
    actions:
      - name:        help
        description: Display help

      - name:        version
        description: Display version

  - name:            backup
    description:     The current backup
    actions:
      - name:        create
        description: Create backup

      - name:        read
        description: View backup

      - name:        update
        description: Re-create backup

      - name:        destroy
        description: Destroy backup

      - name:        metadata
        description: View backup metadata

  - name:            manifest
    description:     List of all files in the archive
    actions:
      - name:        create
        description: Create manifest

      - name:        read
        description: View manifest

      - name:        update
        description: Re-create manifest

      - name:        destroy
        description: Destroy manifest

      - name:        metadata
        description: View manifest metadata

  - name:            records
    description:     List of files excluded from the archive, but kept a record of
    actions:
      - name:        create

        description: Create records
      - name:        read

        description: View records
      - name:        update

        description: Re-create records
      - name:        destroy
        description: Destroy records

      - name:        metadata
        description: View records metadata

  - name:            archive
    description:     Archive of files in the manifest
    actions:
      - name:        create
        description: Create archive

      - name:        read
        description: View archive

      - name:        update
        description: Re-create archive

      - name:        destroy
        description: Destroy archive

      - name:        metadata
        description: View archive metadata

  - name:            checksum
    description:     Archive checksum
    actions:
      - name:        create
        description: Create checksum

      - name:        read
        description: View checksum

      - name:        update
        description: Re-create checksum

      - name:        destroy
        description: Destroy checksum

      - name:        verify
        description: Verify checksum

  - name:            metadata
    description:     Information about the backup
    actions:
      - name:        create
        description: Create metadata

      - name:        read
        description: View metadata

      - name:        update
        description: Update metadata

      - name:        destroy
        description: Destroy metadata

  - name:            config
    description:     Current configuration
    actions:
      - name:        create
        description: Create config

      - name:        read
        description: View config

      - name:        update
        description: Update config

      - name:        destroy
        description: Destroy config

      - name:        view
        description: View config without creating config file

  - name:            log
    description:     Log
    actions:
      - name:        read
        description: View log

      - name:        destroy
        description: Destroy log

